### ISSUE TITLE
"latest" tag gives manifest error in Docker hub

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Broadsea-Achilles#10]
`docker pull ohdsi/broadsea-achilles:latest 
Error response from daemon: manifest for ohdsi/broadsea-achilles:latest not found: manifest unknown: manifest unknown`

**Comment by alondhe** [comment]
Missed the note that release tags should be used over "latest"

**Comment by chgl** [comment]
Being the root cause, I think it's still a bug since the readme references a non-existent image tag. It could be replaced by `master`, or one of the `sha-` tags corresponding to commits.
